### ISSUE TITLE
Use switch statement with type checking for ActionEnums

### ISSUE THREAD

**Issue by Silthus** [LMFinney/ngrx-enums#1]
Is it still possible to use the switch statement instead of the complicated ReducerEnum classes? How would I check the payload type of the actions?

The switch statement has the possibility to fall through several actions, which the ReducerEnum cannot do.

**Comment by LMFinney** [comment]
> Is it still possible to use the switch statement instead of the complicated ReducerEnum classes? 

Yes, you can use just the ActionEnum side of this approach without using the ReducerEnum side (though the reverse isn't true).

> How would I check the payload type of the actions?

You can use the `.type` field of the action to get the string that shows the type.

> The switch statement has the possibility to fall through several actions, which the ReducerEnum cannot do.

This is not true. If you look at the SEARCH_COMPLETE reducer in the [book.ts](https://github.com/LMFinney/ngrx-example-app-enums/blob/master/src/app/reducers/books.ts) file in [ngrx-example-app-enums](https://github.com/LMFinney/ngrx-example-app-enums), you'll see that it can take both `BookActionEnum.SEARCH_COMPLETE` and `CollectionActionEnum.LOAD_SUCCESS` by taking a single action or an array of actions.
